name: Komac
on:
  workflow_dispatch:
    inputs:
      command:
        description: command
        required: true
        type: string
jobs:
  komac:
    runs-on: ubuntu-latest
    steps:
      - name: komac
        uses: michidk/run-komac@v2
        with:
          args: |
            --version
            komac token add --token ${{ secrets.WINGET_TOKEN }}
            ${{ inputs.command }}
